env:
  node: true
  es2020: true

extends: 
  - 'airbnb-base'

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  import/named: 1
  import/extensions: 0
  import/prefer-default-export: 0
  no-await-in-loop: 0
  no-console: 0
